#Configuración del servidor
server.port=8080
spring.application.name=usuarios-service

#Base de datos SQLite independiente para Usuarios
spring.datasource.url=jdbc:sqlite:usuarios.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Clave secreta para JWT (Compartida con el diagrama del instructor)
jwt.secret=s5z2b514R6lrNOwLidNrzT9bHtBnlO+0yO5SOzY3Cdg=
